# Generated by Django 3.2 on 2021-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sorteio', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('numeros_ganhadores', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
